### ISSUE TITLE
In stage one, does anyone know what is the reason?

### ISSUE THREAD

**Issue by zhaoshipeng** [yxgeee/FD-GAN#10]
Epoch: [0][138/809]	Time 31.849 (15.758)	Data 30.354 (14.164)	Loss 0.702 (0.791)	Prec 78.12% (67.82%)	
Traceback (most recent call last):
  File "baseline.py", line 200, in <module>
    main(parser.parse_args())
  File "baseline.py", line 143, in main
    trainer.train(epoch, train_loader, optimizer, base_lr=args.lr)
  File "/content/drive/FDGAN/reid/trainers.py", line 28, in train
    for i, inputs in enumerate(data_loader):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 322, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
OSError: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/content/drive/FDGAN/reid/utils/data/preprocessor.py", line 46, in __getitem__
    return [self._get_single_item(index) for index in indices]
  File "/content/drive/FDGAN/reid/utils/data/preprocessor.py", line 46, in <listcomp>
    return [self._get_single_item(index) for index in indices]
  File "/content/drive/FDGAN/reid/utils/data/preprocessor.py", line 59, in _get_single_item
    img = Image.open(fpath).convert('RGB')
  File "/usr/local/lib/python3.6/dist-packages/PIL/Image.py", line 2609, in open
    fp = builtins.open(filename, "rb")
OSError: [Errno 5] Input/output error: '/content/drive/FDGAN/datasets/market1501/images/00000658_02_0001.jpg'

**Comment by yxgeee** [comment]
Consider about your pytorch version and memory issues.

**Comment by zhaoshipeng** [comment]
Thinks！





At 2018-11-23 14:29:39, "Yixiao Ge" <notifications@github.com> wrote:


Consider about your pytorch version and memory issues.
