### ISSUE TITLE
In stage II: FD-GAN pretraining

### ISSUE THREAD

**Issue by IvyYZ** [yxgeee/FD-GAN#12]
Traceback (most recent call last):
  File "train.py", line 119, in <module>
    main()
  File "train.py", line 53, in main
    model = FDGANModel(opt)
  File "/home/ygcen/zy/Re-id/FD-GAN/fdgan/model.py", line 28, in __init__
    self._init_models()
  File "/home/ygcen/zy/Re-id/FD-GAN/fdgan/model.py", line 58, in _init_models
    self.net_Di.load_state_dict(state_dict)
  File "/home/ygcen/gongjie/install/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for SiameseNet:
	size mismatch for embed_model.classifier.weight: copying a param of torch.Size([1, 2048]) from checkpoint, where the shape is torch.Size([2048]) in current model.

**Comment by yxgeee** [comment]
You can use '.view(-1)' to transfer the checkpoint Tensor with size `[1,2048]` to `[2048]` before loading it.

**Comment by yxgeee** [comment]
You can use `.view(-1)` to transfer the checkpoint Tensor with size [1,2048] to [2048] before loading it.

**Comment by alfredcs** [comment]
Pls explain further. I got a slightly different error. Thx!

Traceback (most recent call last):
  File "train.py", line 119, in <module>
    main()
  File "train.py", line 53, in main
    model = FDGANModel(opt)
  File "/home/aarc/alfred/GAN/PyTorch-GAN/gan4da/FD-GAN/fdgan/model.py", line 28, in __init__
    self._init_models()
  File "/home/aarc/alfred/GAN/PyTorch-GAN/gan4da/FD-GAN/fdgan/model.py", line 59, in _init_models
    self.net_Di.load_state_dict(state_dict).view(-1,2048)
  File "/home/aarc/alfred/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for SiameseNet:
	size mismatch for embed_model.classifier.weight: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1, 2048]).

**Comment by heerduo** [comment]
Hello, I encounter the same problem. Have you solved it?

**Comment by heerduo** [comment]
> Pls explain further. I got a slightly different error. Thx!
> 
> Traceback (most recent call last):
> File "train.py", line 119, in 
> main()
> File "train.py", line 53, in main
> model = FDGANModel(opt)
> File "/home/aarc/alfred/GAN/PyTorch-GAN/gan4da/FD-GAN/fdgan/model.py", line 28, in **init**
> self._init_models()
> File "/home/aarc/alfred/GAN/PyTorch-GAN/gan4da/FD-GAN/fdgan/model.py", line 59, in _init_models
> self.net_Di.load_state_dict(state_dict).view(-1,2048)
> File "/home/aarc/alfred/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
> self.**class**.**name**, "\n\t".join(error_msgs)))
> RuntimeError: Error(s) in loading state_dict for SiameseNet:
> size mismatch for embed_model.classifier.weight: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1, 2048]).

Hello, I encounter the same problem. Have you solved it?
