### ISSUE TITLE
 int() argument must be a string, a bytes-like object or a number, not 'tuple'

### ISSUE THREAD

**Issue by LuoPeng-CV** [yxgeee/FD-GAN#13]
Hello, when I try to pretrain the baseline in stage1,I got a problem.Here is the error imformation,
`Traceback (most recent call last):
  File "train.py", line 121, in <module>
    main()
  File "train.py", line 75, in main
    for i, data in enumerate(train_loader):
  File "/raid/home/kml/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 451, in __iter__
    return _DataLoaderIter(self)
  File "/raid/home/kml/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 247, in __init__
    self._put_indices()
  File "/raid/home/kml/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 295, in _put_indices
    indices = next(self.sample_iter, None)
  File "/raid/home/kml/anaconda3/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 139, in __iter__
    batch.append(int(idx))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'tuple'`

And I download the pretrained models,but when I try to test them,I got the same problem.

I will deeply appreciate it if you could give some advices. Thank you!

**Comment by yang502** [comment]
@Rocccc Excuse me. How do you solve this problem?
