### ISSUE TITLE
In stage I

### ISSUE THREAD

**Issue by Haoru** [yxgeee/FD-GAN#17]
Traceback (most recent call last):
  File "baseline.py", line 201, in <module>
    main(parser.parse_args())
  File "baseline.py", line 118, in main
    top1, mAP = evaluator.evaluate(test_loader, dataset.query, dataset.gallery, rerank_topk=100, dataset=args.dataset)
  File "/media/ouc/4T_B/zhr/FD-GAN/reid/evaluators.py", line 193, in evaluate
    features, _ = extract_features(self.base_model, data_loader)
  File "/media/ouc/4T_B/zhr/FD-GAN/reid/evaluators.py", line 55, in extract_features
    for i, (imgs, fnames, pids, _) in enumerate(data_loader):
  File "/home/ouc/miniconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 330, in __next__
    idx, batch = self._get_batch()
  File "/home/ouc/miniconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 309, in _get_batch
    return self.data_queue.get()
  File "/home/ouc/miniconda3/lib/python3.6/multiprocessing/queues.py", line 337, in get
    return _ForkingPickler.loads(res)
  File "/home/ouc/miniconda3/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 151, in rebuild_storage_fd
    fd = df.detach()
  File "/home/ouc/miniconda3/lib/python3.6/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/home/ouc/miniconda3/lib/python3.6/multiprocessing/reduction.py", line 182, in recv_handle
    return recvfds(s, 1)[0]
  File "/home/ouc/miniconda3/lib/python3.6/multiprocessing/reduction.py", line 161, in recvfds
    len(ancdata))
RuntimeError: received 0 items of ancdata
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fed741f2080>>
Traceback (most recent call last):
  File "/home/ouc/miniconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 399, in __del__
    self._shutdown_workers()
  File "/home/ouc/miniconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 378, in _shutdown_workers
    self.worker_result_queue.get()
  File "/home/ouc/miniconda3/lib/python3.6/multiprocessing/queues.py", line 337, in get
    return _ForkingPickler.loads(res)
  File "/home/ouc/miniconda3/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 151, in rebuild_storage_fd
    fd = df.detach()
  File "/home/ouc/miniconda3/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/ouc/miniconda3/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/ouc/miniconda3/lib/python3.6/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/home/ouc/miniconda3/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

I have encountered this problem during the training and testing process in stage I. Can you give me some help?

**Comment by yxgeee** [comment]
Maybe you can refer to https://github.com/yxgeee/FD-GAN/issues/8#issue-378722851

**Comment by Haoru** [comment]
Thinks for your answer.  The problem has been solved. I want to use my own dataset, can I change the pose to openpose?  @yxgeee

**Comment by yxgeee** [comment]
You can use openpose to generate landmarks for your dataset
