### ISSUE TITLE
The last model cannot be generated

### ISSUE THREAD

**Issue by Haoru** [yxgeee/FD-GAN#23]
I encountered the following problem when I trained the III step. It has been trained, but the model can't be saved. Could you give me some help?

Traceback (most recent call last):
  File "train.py", line 117, in <module>
    main()
  File "train.py", line 96, in main
    mAP = evaluator.evaluate(val_loader, dataset.val, dataset.val, top1=False)
NameError: name 'val_loader' is not defined

**Comment by liulitianji** [comment]
Hello, I encounter the same problem. Have you solved it?

**Comment by yxgeee** [comment]
It is a mistake that I missed the `val_loader` when re-arranging the code.
You could follow https://github.com/yxgeee/FD-GAN/blob/master/baseline.py#L59 to create the val loader.
@liulitianji @Haoru

**Comment by Haoru** [comment]
The problem has been solved.
I missed the val_loader in my training.
Thank you very much~
