### ISSUE TITLE
File not found error on using trained model for testing

### ISSUE THREAD

**Issue by harshj94** [yxgeee/FD-GAN#33]
Getting the following error:

(base) username@user:~/abc/FD-GAN$ python baseline.py -b 256 -d market1501 -a resnet50 --evaluate --resume best_net_E.pth.tar
Traceback (most recent call last):
  File "baseline.py", line 200, in <module>
    main(parser.parse_args())
  File "baseline.py", line 84, in main
    sys.stdout = Logger(osp.join(log_dir, 'log_test.txt'))
  File "/home/xyz/FD-GAN/reid/utils/logging.py", line 13, in __init__
    mkdir_if_missing(os.path.dirname(fpath))
  File "/home/xyz/FD-GAN/reid/utils/osutils.py", line 8, in mkdir_if_missing
    os.makedirs(dir_path)
  File "/home/pqr/anaconda3/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''

**Comment by yxgeee** [comment]
Please double check the arg `--resume`, which directs the absolute path for `best_net_E.pth.tar`.
