### ISSUE TITLE
OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by absagargupta** [yxgeee/FD-GAN#44]
I was running the command python baseline.py -b 16 -j 4 -d market1501 -a resnet50 --combine-trainval --lr 0.01 --epochs 100 --step-size 40 --eval-step 5

and getting the above said error. Here is the full traceback
Extract Features: [968/1206]	Time 0.058 (0.058)	Data 0.003 (0.004)	
Traceback (most recent call last):
  File "baseline.py", line 200, in <module>
  File "baseline.py", line 160, in main
  File "/home/sagar18174/Thesis/person_RE-identification/FD-GAN/reid/evaluators.py", line 193, in evaluate
  File "/home/sagar18174/Thesis/person_RE-identification/FD-GAN/reid/evaluators.py", line 55, in extract_features
  File "/home/sagar18174/.local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
  File "/home/sagar18174/.local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 841, in _next_data
  File "/home/sagar18174/.local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 808, in _get_data
  File "/home/sagar18174/.local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 761, in _try_get_data
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 135, in get
  File "/home/sagar18174/.local/lib/python2.7/site-packages/torch/multiprocessing/queue.py", line 22, in recv
  File "/usr/lib/python2.7/pickle.py", line 1388, in loads
  File "/usr/lib/python2.7/pickle.py", line 864, in load
  File "/usr/lib/python2.7/pickle.py", line 1139, in load_reduce
  File "/home/sagar18174/.local/lib/python2.7/site-packages/torch/multiprocessing/reductions.py", line 287, in rebuild_storage_fd
  File "/usr/lib/python2.7/multiprocessing/reduction.py", line 155, in rebuild_handle
  File "/usr/lib/python2.7/multiprocessing/connection.py", line 169, in Client
  File "/usr/lib/python2.7/multiprocessing/connection.py", line 320, in SocketClient
OSError: [Errno 24] Too many open files

Any idea why this might be happening

**Comment by yxgeee** [comment]
It seems the problem with your CPU I/O. Try to set a smaller value of num_workers for the data loader.
